### ISSUE TITLE
Processing 1:n relations

### ISSUE THREAD

**Issue by AdrianSkierniewski** [aedart/data-transfer-object-dto#1]
Hi,
I'd like to ask if I can use this package for instances that use 1:n relations. In other words, I don't have single `Address` but array or Laravel collection of addresses.

I manage to test it with something like this:
```
    public function setTranslations(Array $translations)
    {
        $this->translations = collect($translations)->map(function ($translation) {
            return new RouteTranslation($translation);
        });
    }
```
In this case standard `DTO->toArray()` won't work with nested collection.
I used `collect` just to have easier access for those DTO's later

Do you have any thoughts about this kind of use case?

**Comment by aedart** [comment]
In theory you should be able to. But as you mentioned, my default `toArray()` implementation does not handle laravel collections, nor any object conversion for that matter. Thus, you need to overwrite the `toArray()`.

For instance (not sure if this will work as you might expect)

```php
    public function toArray()
    {
        $properties = $this->populatableProperties();
        $output = [];
        foreach ($properties as $property) {
            // Make sure that property is not unset
            if (!isset($this->$property)) {
                continue;
            }


            // Get the value
            $value = $this->__get($property);      

            // Check if given is an object... or collection
            if($value instanceof Collection){
                // Do something with value...  e.g. array walk, map... etc.
            }
            
            // Finally, add property value to output
            $output[$property] = $value;

            // Default handling... disable it
            //$output[$property] = $this->__get($property);
        }
        return $output;
    }
```

Of course, it's just an example. You might also have to tinker with the `populate` method, if it must be able to handle other kinds of hydration strategies.

Also, in case that you have a very large data structure, e.g. over 100 items from database, I recommend that you create an [Iterator](http://php.net/manual/en/class.arrayiterator.php) or consider [yield generators](http://php.net/manual/en/language.generators.syntax.php#control-structures.yield). Otherwise your memory might peek a lot, depending on amount of items and how complex they are.

Hopefully this helps you in the right way.

**Comment by AdrianSkierniewski** [comment]
Hi,

First of all, Thank you for such a quick response.
I could always use plain arrays to store `RouteTranslation` in it. But Laravel collections gives me a lot of useful functions. I agree that it will add more complexity and more memory will be needed.
I'm wondering how much items I could handle using Laravel Collections. Isn't the Laravel collection implements iterator?

I'm trying to find something that would decouple Eloquent models from rest of my application. I'm planning to reduce Eloquent models usage, and use them only in my service layer. Service layer should accept only DTO's and returns DTO's. Your DTO's package looks very promising but I'm still trying to figure out if it covers all cases, and that 1:n relations is something that I came across at the beginning.

Next thing is that right now I'm using fractal transformers to transform Eloquent models in my API and I'm wondering if I could just unify everything with those DTO's instead. So my service layer would just return DTO and I can use it in templates (blade), api response (json) and in other places. I could remove transformers and just use DTO's.

Are you planning to add that kind of feature in future (collections, plain arrays) so it would work a little similar to fractal transformers? Eventually how you'd solve that problem in another way?

**Comment by aedart** [comment]
Hi again

"_[...] I could always use plain arrays to store RouteTranslation in it. But Laravel collections gives me a lot of useful functions [...]_"
But you should also be able to simple use the `Collection` object directly. Having a getter and setter that accepts a collection is a valid choice. (**note**: I can't remember if the populate method handles this automatically, ... but it should, otherwise this can be added easily)

"_[...] Isn't the Laravel collection implements iterator?_"
Yes it is - however, it really depends on what you are doing with it. If you iterate a single time throughout the collection, then there is no problem. But several iterations will of course be slow. Sometimes it's easy to get a bit lost in the process, when using multiple models, objects, etc.

"_[...] I'm trying to find something that would decouple Eloquent models from rest of my application [...]_"
Okay, sure - if your application requires this, then you should of course go for such a design. DTO's (this package or other kinds of implementation) might be a good way to achieve such decoupling.
Nevertheless, you should also know that working with Eloquent (Active Record) by itself is no crime. Consider, for instance, [Eloquent's Serialisation method](https://laravel.com/docs/5.5/eloquent-serialization), which you can take advantage of. You hide what you do not need, etc.

"_[...] Next thing is that right now I'm using fractal transformers to transform Eloquent models in my API [...]_"
Using [Fractal](http://fractal.thephpleague.com/transformers/), as you mention, is also a good alternative to my package. I designed this DTO package for this reason:

* When there is a strong need to interface DTOs

E.g. when I have declared a `Person` object and it "must" have a `setName` and `getName` explicitly declared. That being said, having DTOs declared by interfaces isn't always a good thing, in terms of efficiency; it can take forever to write all those objects. If the purpose is to expose certain data (models / objects) via a Json API, then perhaps using transformers are a better (or at least faster) way of doing so.

In addition to this, have you looked at [Eloquent's API Resources](https://laravel.com/docs/5.5/eloquent-resources)... It's kinda similar to Fractal, in that you design a transformer to obtain what data you want to expose for you API. You might even argue that the end result - the data you expose - is a DTO in itself.

"_[...] Are you planning to add that kind of feature in future (collections, plain arrays) [...]_"
Well, I think arrays are covered, and hopefully collections just work out of the box. But it is not my intension to offer "transforming" of data as part of this package. As mentioned Fractal and Eloquent's API Resources appear to have this well covered.

"_[...] Eventually how you'd solve that problem in another way? [...]_"
I would strongly consider the need for interfaced DTOs - if required, then I would start implementing 1-2 complex DTOs and see how well it fits in the overall solution.
But, if I do not require my data to be represented via DTOs (well... as interfaced objects in this case), then I would perhaps stick to the simplest solution possible. This might appear to be Laravel's [API Resources](https://laravel.com/docs/5.5/eloquent-resources) ~ their native transformers. They also offer some pagination helpers, etc.

Lastly, personally I'm using my own package for situations where data is common from an external party. Then I wrap it inside a few strongly defined DTOs, before I then pass them on to processing, e.g. into database, files... logs... or whatever I require. This helps me a lot, because I gain better control of the data, but for APIs (when I deliver data via Json), I actually just settle for using the `toJson` method, which I overwrite to export only what I see fitting for a model (when using Laravel).

I hope this gives you some help with the matter.

**Comment by AdrianSkierniewski** [comment]
Thank you for detailed answers to all my questions. For me, it's always a trade-off - adding more structure vs RAD. I'd like to have my business logic separated from the rest of my app but I know that there is no silver bullet for this. If I'll add an additional layer then I'll find other problems to solve on that road.
It's rather a question which boundaries do I want to force using implementation and which should be just respected by other programmers and validated during code review. If I want to add service layer with business logic - "Am I fine with returning Eloquent model with all its relations and lazy loading to speed up development instead of adding DTO's?". 
I see another potential benefit of using DTO's here. I could treat them as some kind of View Models, so then I can eliminate Transformers, Presenters and replace them with DTO. In some cases (for example. custom reports) you're just making custom SQL with columns from different models, and in that case, it would be nice to create separate DTO for it. The same for 3rd party responses as you mentioned. I don't need Eloquent models for that.

I'm closing this ticket, Thank you for helping me with this problem. I'd need some time to test some different approaches and chose something that fits all my needs.
